version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - MayhemYDG
  - oohnoitz
  ignore:
  - dependency-name: ava
    versions:
    - ">= 3.a, < 4"
  - dependency-name: prebuild-install
    versions:
    - 6.0.0
    - 6.0.1
    - 6.1.1
