# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    node8_linux:
      node_version: 8.x
      imageName: 'ubuntu-latest'
    node8_macOS:
      node_version: 8.x
      imageName: 'macOS-latest'
    node8_windows:
      node_version: 8.x
      imageName: 'vs2017-win2016'
    node10_linux:
      node_version: 10.x
      imageName: 'ubuntu-latest'
    node10_macOS:
      node_version: 10.x
      imageName: 'macOS-latest'
    node10_windows:
      node_version: 10.x
      imageName: 'vs2017-win2016'
    node11_linux:
      node_version: 11.x
      imageName: 'ubuntu-latest'
    node11_macOS:
      node_version: 11.x
      imageName: 'macOS-latest'
    node11_windows:
      node_version: 11.x
      imageName: 'vs2017-win2016'
    node12_linux:
      node_version: 12.x
      imageName: 'ubuntu-latest'
    node12_macOS:
      node_version: 12.x
      imageName: 'macOS-latest'
    node12_windows:
      node_version: 12.x
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  fetchDepth: 1
  submodules: recursive

- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- bash: |
    node --version
    npm --version
  displayName: 'Log node and npm versions'

- bash: npm install --build-from-source
  displayName: 'Install'

- bash: npm test
  displayName: 'Test'

- bash: npm run prebuild-ci
  displayName: 'Build'
